-- AlterTable
ALTER TABLE "post_media_tag" ALTER COLUMN "pointX" SET DEFAULT 0,
ALTER COLUMN "pointX" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "pointY" SET DEFAULT 0,
ALTER COLUMN "pointY" SET DATA TYPE DOUBLE PRECISION;
