-- AlterTable
ALTER TABLE "story_tags" ADD COLUMN     "pointX" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "pointY" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "story_urls" ADD COLUMN     "pointX" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "pointY" INTEGER NOT NULL DEFAULT 0;
